01.Materi.University.Web/Controllers/AgamaController.cs
using _02.Materi.University.DataAccess;
using _03.Materi.University.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _01.Materi.University.Web.Controllers
{
    public class AgamaController : Controller
    {
        // GET: Agama
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult List()
        {
            return View(AgamaDataAccess.GetListAll());
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(AgamaViewModel paramModel)
        {
            try
            {
                paramModel.created_by = "adit";
                paramModel.created_date = DateTime.Now;
                paramModel.updated_by = "adit";
                paramModel.updated_date = DateTime.Now;

                if (AgamaDataAccess.Insert(paramModel))
                {
                    return Json(new { success = true, message = "Data berhasil ditambahkan!" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = true, message = AgamaDataAccess.Message }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception hasError)
            {
                return Json(new { success = true, message = hasError.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult Edit(int paramId)
        {
            return View(AgamaDataAccess.GetDetailsByid(paramId));
        }
        [HttpPost]
        public ActionResult Edit(AgamaViewModel paramModel)
        {
            try
            {
                paramModel.updated_by = "adit";
                paramModel.updated_date = DateTime.Now;

                if (AgamaDataAccess.Update(paramModel))
                {
                    return Json(new { success = true, message = "Data berhasil ditambahkan!" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = true, message = AgamaDataAccess.Message }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception hasError)
            {
                return Json(new { success = true, message = hasError.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult Details(int paramId)
        {
            return View(AgamaDataAccess.GetDetailsByid(paramId));
        }

    }
}

01.Materi.University.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _01.Materi.University.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

01.Materi.University.Web/Views/Agama/Create.cshtml
@model _03.Materi.University.ViewModel.AgamaViewModel

<div class="modal-body">
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.kode_agama, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kode_agama, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kode_agama, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.deskripsi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.deskripsi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.deskripsi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.is_active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.is_active)
                @Html.ValidationMessageFor(model => model.is_active, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>

</div>

<div class="modal-footer">
    <input type="button" value="Save" title="Save" class="btn btn-primary" id="btn_create_save" />
    <input type="button" value="Cancel" title="Cancel" class="btn btn-default" id="btn_create_cancel" data-dismiss="modal" />
</div>

<script>
    $("#btn_create_save").click(function () {
        var item = {
            id_agama_pk: 0,
            kode_agama: $("#kode_agama").val().toUpperCase(),
            deskripsi: $("#deskripsi").val(),
            is_active: $("#is_active").is(":checked")
        };

        $.ajax({
            url: '@Url.Action("Create", "Agama")',
            type: 'post',
            data: { paramModel: item },
            success: function (result) {
                if (result.success) {
                    $("#modal-edit-form").modal("hide");
                    ShowList();
                }
                else {
                    alert(result.message);
                }
            }
        });
    });
</script>

01.Materi.University.Web/Views/Agama/Details.cshtml
@model _03.Materi.University.ViewModel.AgamaViewModel

<div class="modal-body">
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.kode_agama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.kode_agama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.deskripsi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.deskripsi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.is_active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.is_active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.created_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created_by)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.created_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.updated_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.updated_by)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.updated_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.updated_date)
        </dd>

    </dl>
</div>

<div class="modal-footer">
    <input type="button" value="Edit" title="Edit" class="btn btn-primary" id="btn_details_edit" data-id="@Html.DisplayFor(model => model.id_agama_pk)" />
    <input type="button" value="Cancel" title="Cancel" class="btn btn-default" id="btn_create_cancel" data-dismiss="modal" />
</div>

<script>
    $("#btn_details_edit").click(function () {
        $(".modal-title").html("Edit Form Agama");
        $(".div-bind-content").html(progHtml);

        $.ajax({
            url: '@Url.Action("Edit", "Agama")',
            type: 'get',
            data: { paramId: $(this).attr("data-id") },
            success: function (result) {
                $(".div-bind-content").html(result);
            }
        });

    });
</script>

01.Materi.University.Web/Views/Agama/Edit.cshtml
@model _03.Materi.University.ViewModel.AgamaViewModel

<div class="modal-body">
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_agama_pk)

        <div class="form-group">
            @Html.LabelFor(model => model.kode_agama, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kode_agama, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kode_agama, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.deskripsi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.deskripsi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.deskripsi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.is_active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.is_active)
                @Html.ValidationMessageFor(model => model.is_active, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>
</div>

<div class="modal-footer">
    <input type="button" value="Save" title="Save" class="btn btn-primary" id="btn_edit_save" />
    <input type="button" value="Cancel" title="Cancel" class="btn btn-default" id="btn_edit_cancel" data-dismiss="modal" />
</div>

<script>
    $("#btn_edit_save").click(function () {
        var item = {
            id_agama_pk: $("#id_agama_pk").val(),
            kode_agama: $("#kode_agama").val().toUpperCase(),
            deskripsi: $("#deskripsi").val(),
            is_active: $("#is_active").is(":checked")
        };

        $.ajax({
            url: '@Url.Action("Edit", "Agama")',
            type: 'post',
            data: { paramModel: item },
            success: function (result) {
                if (result.success) {
                    $("#modal-edit-form").modal("hide");
                    ShowList();
                }
                else {
                    alert(result.message);
                }
            }
        });
    });
</script>

01.Materi.University.Web/Views/Agama/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">

            <button typeof="button" id="btn-add-categories" class="btn btn-success" title="Create New">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Tambah Data
            </button>

        </div>
        <div class="panel-body">

            <div id="table-list">
                <div class="progress progress-striped active" style="margin-bottom:0">
                    <div class="progress-bar" style="width:100%" />
                </div>
            </div>

        </div>
    </div>
</div>


<div id="modal-edit-form" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Modal Header</h4>
            </div>

            <div class="div-bind-content">
                @*<div class="modal-body">
                    <p>Some text in the modal.</p>
                </div>*@

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>

    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        var progHtml = '<div class="progress progress-striped active" style="margin-bottom:0"><div class="progress-bar" style="width:100%"/></div>';

        $(document).ready(function () {
            ShowList();
        });

        function ShowList() {
            $("#table-list").html(progHtml);

            $.ajax({
                url: '@Url.Action("List","Agama")',
                type: 'get',
                success: function (result) {
                    $("#table-list").html(result);
                }
            });
        }

        $("#btn-add-categories").click(function () {
            /* Configurations Modal */
            $("#modal-edit-form").modal("show");
            $(".modal-title").html("Edit Form Agama");
            $(".div-bind-content").html(progHtml);

            /* Show body modal */
            $.ajax({
                url: '@Url.Action("Create","Agama")',
                type: 'get',
                success: function (result) {
                    $(".div-bind-content").html(result);
                }
            })
        });

        $(".btn_edit_grid").click(function () {
            //alert('Id nya adalah :' + $(this).attr("data-id"));
            $("#modal-edit-form").modal("show");
            $(".modal-title").html("Edit Form Agama");
            $(".modal-body").html(progHtml);

            $.ajax({
                url: '@Url.Action("Edit", "Categories")',
                type: 'get',
                data: { id: $(this).attr("data-id") },
                success: function (result) {
                    $("#modal-body").html(result);
                }
            });
    });

    $(".btn_delete_grid").click(function () {
        //alert('Id nya adalah :' + $(this).attr("data-id"));
        $("#modal-title").html("Are you sure you want to delete this Categories?");
        $("#modal-body").html(progHtml);
        $("#modal-form").modal("show");

        $.ajax({
            url: '@Url.Action("Delete", "Categories")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $("#modal-body").html(result);
            }
        });
    });

    </script>
}

01.Materi.University.Web/Views/Agama/List.cshtml
@model IEnumerable<_03.Materi.University.ViewModel.AgamaViewModel>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.kode_agama)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.deskripsi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.is_active)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.created_by)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.created_date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.updated_by)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.updated_date)
        </th>
        <th>
            Action
        </th>
    </tr>

    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.kode_agama)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.deskripsi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.is_active)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.created_by)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.created_date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.updated_by)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.updated_date)
                </td>
                <td>
                    <button title="Edit" class="btn_grid_edit btn btn-warning" data-id="@item.id_agama_pk">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                    </button>
                    <button title="Delete" class="btn_grid_details btn btn-info" data-id="@item.id_agama_pk">
                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                    </button>
                </td>
            </tr>
        }
    }

</table>


<script type="text/javascript">

    $(".btn_grid_edit").click(function () {
        //alert('Id nya adalah :' + $(this).attr("data-id"));
        $("#modal-edit-form").modal("show");
        $(".modal-title").html("Edit Form Agama");
        $(".div-bind-content").html(progHtml);

        $.ajax({
            url: '@Url.Action("Edit", "Agama")',
            type: 'get',
            data: { paramId: $(this).attr("data-id") },
            success: function (result) {
                $(".div-bind-content").html(result);
            }
        });
    });

    $(".btn_grid_details").click(function () {
        //alert('Id nya adalah :' + $(this).attr("data-id"));
        $("#modal-edit-form").modal("show");
        $(".modal-title").html("Detail Agama");
        $(".div-bind-content").html(progHtml);

        $.ajax({
            url: '@Url.Action("Details", "Agama")',
            type: 'get',
            data: { paramId: $(this).attr("data-id") },
            success: function (result) {
                $(".div-bind-content").html(result);
            }
        });
    });

</script>

01.Materi.University.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

01.Materi.University.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

01.Materi.University.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

01.Materi.University.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Master Data
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Agama", "Index", "Agama")</li>
                            <li>@Html.ActionLink("Program Studi", "Index", "Home")</li>
                            <li>@Html.ActionLink("Jenis Karyawan", "Index", "Home")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <br />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>